
language: node_js
node_js:
- "6"
services:
- postgresql

before_script:
  - psql -c 'create database mybooks;' -U postgres
  - sequelize db:migrate

env:
  global:
    - export NODE_ENV=test
    
script:
  - npm test
  - npm install

after_success:
  - npm run coveralls
notifications:
webhooks: https://coveralls.io/webhook?repo_token=Ud5haz1OcFZO4Q0utfAD62uDSs9BfQHzv